release: highlights of v0.0.8
maistra/istio-workspace pull request #727
Opened 2021-03-01 17:21 UTC by aslakknutsen

/skip-e2e

Signed-off-by: Aslak Knutsen <aslak@4fs.no>

2021-03-01 17:22 UTC, aslakknutsen commented
/changelog v0.0.8

2021-03-02 09:33 UTC, aslakknutsen commented
/changelog v0.0.8

2021-03-02 09:40 UTC, bartoszmajsak commented
/help

2021-03-02 09:41 UTC, alien-ike commented
### ℹ️ Available commands

 * `/changelog vX.Y.Z` will append changelog based on the closed PRs since last release to provided release notes.

 * `/release vX.Y.Z` will add release-related commits to this PR on your behalf. 

 * `/shipit` will rebase everything on master branch and trigger actual release process

2021-03-02 09:43 UTC, bartoszmajsak requested changes
Minor wordings suggestion (bulk update with `/skip-e2e`)

2021-03-02 09:43 UTC, bartoszmajsak commented on docs/modules/ROOT/pages/release_notes/v0.0.8.adoc
> +The operator will now watch all the dependent resources (DestinationRule, Gateway, VirtualService, Deployment)
```suggestion
The operator will now watch all the dependent resources (`DestinationRule`, `Gateway`, `VirtualService`, `Deployment`)
```

2021-03-02 09:43 UTC, bartoszmajsak commented on docs/modules/ROOT/pages/release_notes/v0.0.8.adoc
> +and reconcile the Session on any change.
```suggestion
and reconcile the `Session` on any change.
```

2021-03-02 09:43 UTC, bartoszmajsak commented on docs/modules/ROOT/pages/release_notes/v0.0.8.adoc
> +This means that even if a 3. party tool reconfigures the current state, overwrites it, or pushes new releases, the operator will ensure that the special route is still operational.
```suggestion
This means that even if a third-party tool reconfigures the current state, overwrites it, or pushes new releases, the operator will ensure that the special route is still operational.
```

2021-03-02 09:54 UTC, aslakknutsen commented
/changelog v0.0.8

2021-03-02 09:55 UTC, aslakknutsen commented
@bartoszmajsak merged, rebased and squashed..

2021-03-02 10:05 UTC, aslakknutsen commented
/release v0.0.8

2021-03-02 10:31 UTC, bartoszmajsak approved these changes

2021-03-02 10:31 UTC, aslakknutsen commented
/shipit

2021-03-02 10:32 UTC, merged

2021-03-02 10:32 UTC, alien-ike commented
🎇 🎉 🎆 New version has been shipped! 🚀🚀🚀