fix(operatorhub): uses ansible test scripts from new repo
maistra/istio-workspace pull request #910
Opened 2021-09-16 13:41 UTC by bartoszmajsak

#### Short description of what this resolves:

As operatorhub repository has been split into two locations this affected the ansible-based test harness we use for the release process. This fix corrects the location from where we download it.

This can be further improved when https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/pull/244 is accepted and merged.

#### Changes proposed in this pull request:

- updated test script downloading ansible testing harness from new repository
- new Make target `bundle-test` which will execute tests in `--dry-run` mode
- GitHub Action for testing bundle using newly created target

Fixes #890

2021-09-17 11:28 UTC, bartoszmajsak commented
Script has a workaround right now because ansible-based test harness exits with `0` regardless of actual test status. This leads to false positives in GH Action. See https://github.com/redhat-openshift-ecosystem/operator-test-playbooks/pull/247

2021-09-20 08:02 UTC, aslakknutsen requested changes

2021-09-20 08:02 UTC, aslakknutsen commented on Makefile
> +bundle-test: bundle	## Open up a PR to the Operator Hub community catalog
```suggestion
bundle-test: bundle	## Run the Operator Hub test suite
```

2021-09-20 09:13 UTC, aslakknutsen approved these changes

2021-09-20 09:19 UTC, bartoszmajsak commented
Fixes #890

2021-09-20 09:19 UTC, merged